[CLO-40] - Make updateFromJson doc save optional
Gene42/phenotips pull request #1
Opened 2018-03-14 18:21 UTC by sebialex

2018-03-14 18:36 UTC, buske approved these changes
Add a TODO to refactor to separate the responsibilities when we migrate to pt-core-1.4, and then it looks good to me

2018-03-14 18:37 UTC, danielpgross approved these changes

2018-03-30 21:12 UTC, danielpgross requested changes
Looks good, aside from these minor changes.

One of us should run through some common cases with the debugger to ensure that the document's `isDirty` flag is being activated on any change within a controller.

2018-03-30 21:12 UTC, danielpgross commented on components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
> +    private static boolean saveIfDirty(XWikiDocument document, boolean saveOnlyIfDirty)
This method name is confusing to me because it implies that the method actually saves the document. How about `shouldSaveDocument` instead?

2018-03-30 21:12 UTC, danielpgross commented on components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
> +        this.updateFromJSON(json, true, true);
Shouldn't the third argument be `saveOnlyIfDirty`?

2018-04-02 15:55 UTC, sebialex commented on components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
> +    private static boolean saveIfDirty(XWikiDocument document, boolean saveOnlyIfDirty)
I'll think about it some more, but I didn't want to call it that because the first boolean 'save' serves that purpose, and the method deals with dirty flag. If I called it `shouldSaveDocument`, then I might as well have brought in the first boolean as well, and that would have defeated the purpose.

2018-04-02 15:57 UTC, sebialex commented on components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
> +    private static boolean saveIfDirty(XWikiDocument document, boolean saveOnlyIfDirty)
My concern is that the dirty flag is always true due to some other mechanism, even if nothing changed.

2018-04-02 16:45 UTC, sebialex commented on components/patient-data/impl/src/main/java/org/phenotips/data/internal/PhenoTipsPatient.java
> +        this.updateFromJSON(json, true, true);
Yes

2018-04-02 17:03 UTC, danielpgross approved these changes

2018-04-03 20:11 UTC, merged