NIAID-236
Gene42/phenotips pull request #5
Opened 2019-06-19 16:36 UTC by buske

2019-06-19 18:41 UTC, danielpgross requested changes
Overall this is looking good 👍 

I did basic testing on a new patient and also on an imported patient with ORDO and OMIM terms, to test backwards-compatibility.

On the new patient:
All testing worked fine, there were no bugs or unexpected behaviour to note.

On the imported patient:
- ORDO terms were not shown at all on the patient form or in the pedigree editor
- OMIM terms worked fine on both the patient form and in the pedigree editor

A few notes on my review:
- I did not look in detail at the logic changes to the pedigree editor
- I assumed that all of the vocabulary changes (under `/components/vocabularies/mondo`) were copy/paste and did not look at them in detail

2019-06-19 18:41 UTC, danielpgross commented on components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml
> +  <contentUpdateDate>1559061018000</contentUpdateDate>
In the interest of keeping the commitdiff clean, date changes shouldn't be included.

2019-06-19 18:41 UTC, danielpgross commented on components/patient-data/ui/src/main/resources/PhenoTips/PatientSheetCode.xml
> +  <contentUpdateDate>1558991504000</contentUpdateDate>
Remove

2019-06-19 18:41 UTC, danielpgross commented on components/patient-data/ui/src/main/resources/PhenoTips/UIX_Field__clinical_diagnosis.xml
> +  <contentUpdateDate>1558991504000</contentUpdateDate>
Remove

2019-06-19 18:41 UTC, danielpgross commented on components/pedigree/resources/src/main/resources/pedigree/externalEndpoints.js
> +        getDisorderSuggestURL: function(input) {
Why does this take the `input` argument if it's never used?

2019-06-19 18:41 UTC, danielpgross commented on components/pedigree/resources/src/main/resources/pedigree/disorder.js
> +            var curie = this._disorderID;
[curie](https://www.dictionary.com/browse/curie) is a unit of radioactivity, why is this the variable name?

2019-06-19 18:41 UTC, danielpgross commented on components/vocabularies/mondo/api/src/main/java/org/phenotips/vocabulary/internal/solr/MondoDiseaseOntology.java
> +    /** For determining if a query is a an id. */
Typo `a an`

2019-06-19 18:41 UTC, danielpgross commented on components/widgets/ui/src/main/resources/PhenoTips/Widgets.xml
> +  <contentUpdateDate>1558991510000</contentUpdateDate>
Remove

2019-06-19 19:38 UTC, buske commented on components/pedigree/resources/src/main/resources/pedigree/disorder.js
> +            var curie = this._disorderID;
https://www.w3.org/TR/curie/

There's a nice summary here: https://schemablocks.org/formats/identifiers-curies/
> CURIEs (“Compact URIs”) are namespace-scoped identifiers which can be expanded to Internationalized Resource Identifiers (IRI). A CURIE is comprised of two components, a prefix and a reference, separated by a colon symbol (:). CURIES are case sensitive, although for prefixes this practice is inconsistently being followed.

2019-06-19 19:39 UTC, buske commented on components/patient-data/ui/src/main/resources/PhenoTips/PatientClass.xml
> +  <contentUpdateDate>1559061018000</contentUpdateDate>
I usually would, but I thought we'd changed this policy as per the issues with the distro wizard that @sebialex encountered...

2019-06-19 19:40 UTC, buske commented on components/pedigree/resources/src/main/resources/pedigree/externalEndpoints.js
> +        getDisorderSuggestURL: function(input) {
Good catch, that's definitely a relic from a refactor.

2019-06-19 19:48 UTC, buske commented
> On the imported patient:
> * ORDO terms were not shown at all on the patient form or in the pedigree editor
> * OMIM terms worked fine on both the patient form and in the pedigree editor

👍 This is because the PR extends the behaviour of the OMIM field and the ORDO field is hidden. This is sufficient to meet the client reqs.

2019-06-19 19:52 UTC, buske commented
>     * I did not look in detail at the logic changes to the pedigree editor

It would be useful to get your review on the Affected status decoupling commit: https://github.com/Gene42/phenotips/pull/5/commits/d0077d1402b1d39ffff2f10ea63ec0d2c5d5952e

2019-06-19 21:44 UTC, buske commented on components/vocabularies/mondo/api/src/main/java/org/phenotips/vocabulary/internal/solr/MondoDiseaseOntology.java
> +    /** For determining if a query is a an id. */
Looks like this was a typo in the source file (HPO ontology) :(  Will fix.

2019-06-21 15:56 UTC, danielpgross commented on components/pedigree/resources/src/main/resources/pedigree/disorder.js
> +            var curie = this._disorderID;
Good to know, thanks for explaining!

2019-06-21 17:44 UTC, danielpgross commented
Thanks for addressing all the other comments in my last review.

Bug (as discussed in person):
1. Add 2 diagnoses to an individual in the pedigree.
2. Click "Delete all" under the "Diagnosis" field.
3. Only one diagnosis will be deleted and the following error will be logged in the console: `Uncaught TypeError: Cannot read property 'removeChild' of null`

2019-06-21 17:50 UTC, danielpgross commented
Here's a behaviour that I don't think makes sense, although it's not a bug per se:
The `affected` non-standard disorder term is added when selecting "Affected" under carrier status. The `affected` non-standard disorder term is removed if "Not affected" is then selected.
BUT
The `affected` non-standard disorder term is _not_ removed if any other carrier status is then selected.

I think the `affected` non-standard disorder term should be removed if any carrier status other than "Affected" is selected.

2019-06-21 17:58 UTC, danielpgross commented
Here's a behaviour that either does not make sense to me, or is a bug (i.e. I'm not sure if it was intentional). The behaviour was present before your changes, but this is a good time to make a decision about it.
1) With no diagnosis terms selected, change the carrier status to something other than "Affected", e.g. "Carrier".
2) Add a diagnosis term.
3) Remove the diagnosis term. The carrier status is reset to "Not affected".

Instead, I think the carrier status should not be changed when all diagnosis terms are removed.

2019-06-23 17:54 UTC, buske commented
> Thanks for addressing all the other comments in my last review.
> 
> Bug (as discussed in person):
> 
>     1. Add 2 diagnoses to an individual in the pedigree.
> 
>     2. Click "Delete all" under the "Diagnosis" field.
> 
>     3. Only one diagnosis will be deleted and the following error will be logged in the console: `Uncaught TypeError: Cannot read property 'removeChild' of null`

After investigating further, this is a bug in 1.3.x unrelated to this PR and is fixed in 1.4.

2019-06-23 17:56 UTC, buske commented
> any

As discussed, this is probably the best of the available options for how this should behave.

2019-06-24 03:59 UTC, buske commented
> Here's a behaviour that either does not make sense to me, or is a bug (i.e. I'm not sure if it was intentional). The behaviour was present before your changes, but this is a good time to make a decision about it.
> 
>     1. With no diagnosis terms selected, change the carrier status to something other than "Affected", e.g. "Carrier".
> 
>     2. Add a diagnosis term.
> 
>     3. Remove the diagnosis term. The carrier status is reset to "Not affected".
> 
> 
> Instead, I think the carrier status should not be changed when all diagnosis terms are removed.

Agree, this is a bug and vestigial behaviour. I've pushed a new commit that fixes this behaviour and simplifies some of the affected status logic.

2019-06-24 21:58 UTC, danielpgross approved these changes
Looks good 👍

2019-06-26 22:52 UTC, buske commented
Closing, since this isn't intended to be merged into master.

2019-06-26 22:52 UTC, closed without merging